name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - name: Build & Test
      run: |
        go build -v
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        args: release --snapshot --skip-publish --clean
        GITHUB_TOKEN: ${{ secrets.GH_PAT3 }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT3 }}
    - name: Colored Output Test
      if: runner.os == 'Linux'
      shell: script -q -e -c "bash {0}"
      run: go run main.go --help


